stages:
  - build-npm
  - build-docker

cache:
  paths:
    - ./dist
    - ./node_modules
    
npm-build:
  image: node:14-alpine3.14
  stage: build-npm
  script:
    - npm install
    - npm install -g @vue/cli
    - npm run build

docker-build:
  image: docker:dind
  stage: build-docker
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - main
